package org.gallery.nativemethod;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u989c\u8272\u5339\u914d\u7684\u914d\u8272\u5bf9<br>
 * <i>native declaration : ImageConvertDll.h:25</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("ImageConvertDll") 
public class ccMatchLinks extends StructObject {
	@Field(0) 
	public int nNumLink() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public ccMatchLinks nNumLink(int nNumLink) {
		this.io.setIntField(this, 0, nNumLink);
		return this;
	}
	/** C type : ccLink* */
	@Field(1) 
	public Pointer<ccLink > pLinks() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : ccLink* */
	@Field(1) 
	public ccMatchLinks pLinks(Pointer<ccLink > pLinks) {
		this.io.setPointerField(this, 1, pLinks);
		return this;
	}
	public ccMatchLinks() {
		super();
	}
	public ccMatchLinks(Pointer pointer) {
		super(pointer);
	}
}
