package org.gallery.nativemethod;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : ImageConvertDll.h:4</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("ImageConvertDll") 
public class ccRegion extends StructObject {
	@Field(0) 
	public int count() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public ccRegion count(int count) {
		this.io.setIntField(this, 0, count);
		return this;
	}
	/** C type : int* */
	@Field(1) 
	public Pointer<Integer > x() {
		return this.io.getPointerField(this, 1);
	}
	/** C type : int* */
	@Field(1) 
	public ccRegion x(Pointer<Integer > x) {
		this.io.setPointerField(this, 1, x);
		return this;
	}
	/** C type : int* */
	@Field(2) 
	public Pointer<Integer > y() {
		return this.io.getPointerField(this, 2);
	}
	/** C type : int* */
	@Field(2) 
	public ccRegion y(Pointer<Integer > y) {
		this.io.setPointerField(this, 2, y);
		return this;
	}
	public ccRegion() {
		super();
	}
	public ccRegion(Pointer pointer) {
		super(pointer);
	}
}
