package com.gallery.nativemethod;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u5b9a\u4e49\u989c\u8272\u7684\u6620\u5c04<br>
 * <i>native declaration : ImageConvertDll.h:20</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("ImageConvertDll") 
public class ccLink extends StructObject {
	/** nSrcIndex: \u6e90\u56fe\u50cf\u989c\u8272\u98ce\u683c\u4e2d\u7684\u989c\u8272\u5e8f\u53f7 */
	@Field(0) 
	public int nSrcIndex() {
		return this.io.getIntField(this, 0);
	}
	/** nSrcIndex: \u6e90\u56fe\u50cf\u989c\u8272\u98ce\u683c\u4e2d\u7684\u989c\u8272\u5e8f\u53f7 */
	@Field(0) 
	public ccLink nSrcIndex(int nSrcIndex) {
		this.io.setIntField(this, 0, nSrcIndex);
		return this;
	}
	/** nSrcIndex: \u6e90\u56fe\u50cf\u989c\u8272\u98ce\u683c\u4e2d\u7684\u989c\u8272\u5e8f\u53f7 */
	@Field(1) 
	public int nDestIndex() {
		return this.io.getIntField(this, 1);
	}
	/** nSrcIndex: \u6e90\u56fe\u50cf\u989c\u8272\u98ce\u683c\u4e2d\u7684\u989c\u8272\u5e8f\u53f7 */
	@Field(1) 
	public ccLink nDestIndex(int nDestIndex) {
		this.io.setIntField(this, 1, nDestIndex);
		return this;
	}
	public ccLink() {
		super();
	}
	public ccLink(Pointer pointer) {
		super(pointer);
	}
}
